User's Guide
------------

Less theory, more practice. Usually we have no time and desire to read lengthy docs,
so this part is more or less like "How To". If you prefer more detailed and strict docs, 
Sphinxit has documented :ref:`API`. Also, you always can explore tests and sources, 
it`s quite useful for understanding internal project architecture.

.. toctree::
   :maxdepth: 2

   installation
   quickstart
   searching
   filtering
   snippets
   integration
   
.. toctree::
   :maxdepth: 2

   api
   changelog


Development
-----------

You can grab `latest code at Github <https://github.com/semirook/sphinxit>`_. Feel free to submit issues and pull requests.

Contact
-------

If you have some private proposals or specific questions,
find me in `Twitter <https://twitter.com/semirook>`_ or `Facebook <http://www.facebook.com/semirook>`_.
